seconds=int(input("Введите количество секунд:"))
print("Количество дней:",seconds//(3600*24))
print("Количество часов:",seconds//3600)
print("Количество минут:",seconds//60)
print("Количество секунд",seconds)